version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    build: ./postgres/
    volumes:
      - ./postgres/pgdata:/pgdata
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=balance_db
      - PGDATA=/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres || exit 1" ]
      interval: 10s
      timeout: 15s
      retries: 3
  server:
    build: ./server/
    volumes:
      - ./log:/server/log/
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8080/actuator/health || exit 1" ]
      interval: 2s
      timeout: 15s
      retries: 15
  client:
    build: ./client/
    volumes:
      - ./log:/client/log/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      server:
        condition: service_healthy
